apiVersion: v1
kind: Service
metadata:
    name: {{ include "rest-controller.fullname" . }}
    labels:
        app: {{ include "rest-controller.name" . }}
spec:
    type: ClusterIP
    selector:
        app: {{ include "rest-controller.name" . }} #monitor on pod tag as in deployment
    ports: #target port
    - port: {{ .Values.service.port }} 
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.debugPort }}
      targetPort: {{ .Values.service.debugPort }}
      protocol: TCP
      name: debug